apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-z8wb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0012-tenant/tkrw-pr712-0075-0012-app/devfile-sample-z8wb@sha256:b4ac48d166d3c26aadc17938c748eadea292d26c694e94013c1795cb5eb0dda5
        name: my-nodejs
        resources: {}
status: {}
